### ISSUE TITLE
FPS still capped at 60

### ISSUE THREAD

**Issue by garylisk** [Lyall/DQ3Fix#1]
The FPS unlock is set to true in the ini file, but the FPS is still capped at 60. Otherwise, all the other features are working fine. Tried Fullscreen and Borderless. My monitor is 1400p 144Hz. Running Pop!_OS Linux, using Proton 9.0-3 in Steam (flatpak). I am using Steam's built-in FPS counter, I assume it is accurate. (top right corner of included screen capture)
![2024-11-27_21-14](https://github.com/user-attachments/assets/3a06b67d-ceb3-4545-b5a2-0d55ce7ceb25)

**Comment by Lyall** [comment]
Can you post your `DQ3Fix.log` file? It should be next to the main game executable.

**Comment by garylisk** [comment]
Sure thing!
[DQ3Fix.log](https://github.com/user-attachments/files/17942690/DQ3Fix.log)

**Comment by garylisk** [comment]
Additional: It seems to be working fine on my Steam Deck, despite the deck's display being 60 Hz, the unlocked framerate goes beyond, hits almost 90fps.

**Comment by garylisk** [comment]
This issue has been resolved: The vsync option inside the game has to be toggled off to unlock framerate, it appears.

**Comment by Lyall** [comment]
> This issue has been resolved: The vsync option inside the game has to be toggled off to unlock framerate, it appears.

That's an odd one. You should be able to use vSync as expected in game. I don't think UE4 has any capability specifically for half/third-rate vSync so it should be limiting you to 144FPS. Perhaps something in Proton is causing the game to launch at 60Hz?

**Comment by garylisk** [comment]
Odd, but I recall a similar issue with World of Warcraft at one point, where some setting in WINE was doing it. I am not sure what I could even do inside Steam/Proton to check, though. BTW with vsync off, the game goes up to over 200fps.

**Comment by garylisk** [comment]
I found a hacky workaround to limit to my monitor's refresh rate. Added DXVK_FRAME_RATE=144 to the launch options in Steam, and now it's locked to 144fps as long as in-game vsync is disabled.

**Comment by Lyall** [comment]
Do you have multiple displays? I'm wondering if DXVK or your compositor is limiting it to another monitors highest refresh rate. A better solution might be forcing vSync externally (though I'm not sure what the options for that are in Proton/Linux in general), instead of using the game's built in vSync.

**Comment by garylisk** [comment]
![2024-11-28_00-54](https://github.com/user-attachments/assets/2061ae6c-36eb-4123-9736-e49d227d850a)
I do. My other monitors are 60Hz, but the primary display is 144.

**Comment by Lyall** [comment]
> I do. My other monitors are 60Hz, but the primary display is 144.

Ah I wonder if that's the cause. Do you use Wayland? If I recall correctly this used to be an issue with X11 and the Nvidia driver where it would use the refresh rate of the slowest display.

**Comment by garylisk** [comment]
I am in pop OS, it uses X11, so perhaps that's the case.

Edit: I will try to enable wayland tomorrow and see if that changes things.

**Comment by garylisk** [comment]
Thank you so much for your knowledge and willingness to troubleshoot what turned out to not be an issue with your mod, but an issue with X11. Switching to Wayland and then enabling vsync was the solution.

**Comment by Lyall** [comment]
> Thank you so much for your knowledge and willingness to troubleshoot what turned out to not be an issue with your mod, but an issue with X11. Switching to Wayland and then enabling vsync was the solution.

Glad to hear it! I know that Wayland still has some teething issues but it definitely seems like the compositor of choice these days (especially when it comes to gaming).
