### ISSUE TITLE
Uncentered Battle HUD for Ultrawide

### ISSUE THREAD

**Issue by Flametossed** [Lyall/DQ3Fix#5]
Would it be possible to adjust the battle HUD so it is not centered? Currently the menu overlaps the character on screen and it would be nice to have the option to have it out of the way on the side. 

Attached is an example:

![image](https://github.com/user-attachments/assets/58a09d92-3562-474a-9d08-4746cc12abdf)

**Comment by Lyall** [comment]
I've added an option to span parts of the HUD in v0.0.2.

![Dragon Quest Iii Hd-2d Remake Screenshot 2024 11 29 - 02 58 06 63](https://github.com/user-attachments/assets/77d89e94-d271-45c8-aefc-cc37a6a08724)
![Dragon Quest Iii Hd-2d Remake Screenshot 2024 11 29 - 02 57 45 05](https://github.com/user-attachments/assets/233faa6f-90f4-4f34-a061-fa083667b98e)

**Comment by Flametossed** [comment]
Thank you! this was exactly what I was looking for.
