### ISSUE TITLE
False positive in v0.0.2?

### ISSUE THREAD

**Issue by RhinoKneel** [Lyall/DQ3Fix#6]
Windows Defender is currently detecting "Trojan:Script/Wacatac.B!ml" in the main zip file, though no issues occur in downloading the source or v0.0.1. Just hoping others don't hit the same wall, and want to keep things safe.

**Comment by Lyall** [comment]
Seems to be some false-positive flagging event going on at the moment with Microsoft Defender as a few of my other fixes have been flagged too. If anyone is trying to use, you'll need to allow it as an exception in Microsoft Defender, or wait and see if the flag is removed eventually.

https://github.com/Lyall/STALKER2Tweak/issues/11
https://github.com/Lyall/DAFix/issues/2

**Comment by RhinoKneel** [comment]
No issues with the download tonight. Seems it's been smartened up.

**Comment by cb613** [comment]
issue seems to have returned with 0.0.3, same detection Script/Wacatac.B!ml

**Comment by Lyall** [comment]
> issue seems to have returned with 0.0.3, same detection Script/Wacatac.B!ml

Yeah it's probably gonna be a losing battle waiting for each new version to get unflagged by WIndows Defender. Here is a [VirusTotal report](https://www.virustotal.com/gui/file/06b3d91f79d20d887f40d023989eb7f1c2b5897e2bbcf238aee4a17f92492c52) for v0.0.3.
